"""empty message

Revision ID: 112af96eed6c
Revises: 99087c21d472
Create Date: 2024-02-20 15:29:10.442789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112af96eed6c'
down_revision = '99087c21d472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fairies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fairies')
    # ### end Alembic commands ###
