"""empty message

Revision ID: 195aa2f7c995
Revises: 70db6bc5aae6
Create Date: 2024-02-23 21:38:39.780386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195aa2f7c995'
down_revision = '70db6bc5aae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fairy_selected_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fairy_selected_products')
    # ### end Alembic commands ###
