"""empty message

Revision ID: 676f15700d52
Revises: 195aa2f7c995
Create Date: 2024-02-25 22:44:24.027780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676f15700d52'
down_revision = '195aa2f7c995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_title', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('professional_title')

    # ### end Alembic commands ###
