"""empty message

Revision ID: 70db6bc5aae6
Revises: f9abc235c458
Create Date: 2024-02-20 22:43:06.680282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70db6bc5aae6'
down_revision = 'f9abc235c458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fairy_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Enum('ONE_STAR', 'TWO_STARS', 'THREE_STARS', 'FOUR_STARS', 'FIVE_STARS', name='ratingenum'), nullable=False))
        batch_op.drop_constraint('orders_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['fairy_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('rating')
        batch_op.drop_column('fairy_id')
        batch_op.drop_column('client_id')

    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', postgresql.ENUM('ONE_STAR', 'TWO_STARS', 'THREE_STARS', 'FOUR_STARS', 'FIVE_STARS', name='ratingenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rating_pkey')
    )
    # ### end Alembic commands ###
