"""empty message

Revision ID: 9653f9d1f715
Revises: df411a67c933
Create Date: 2024-02-16 01:26:55.235875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9653f9d1f715'
down_revision = 'df411a67c933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.drop_constraint('service_categories_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_category', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_categories', ['service_category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_category')

    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_categories_service_id_fkey', 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###
