"""empty message

Revision ID: 99087c21d472
Revises: 6abcd62268ea
Create Date: 2024-02-20 01:41:20.028181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99087c21d472'
down_revision = '6abcd62268ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fairy_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fairy_products')
    # ### end Alembic commands ###
